version: "3"
services:
  server:
    container_name: seven_nineteen_server
    build: .
    environment:
        - PORT=8080
        - DB_HOST=database
        - DB_DIALECT=mysql
        - DB_NAME=seven_nineteen_db
        - DB_USER=seven_nineteen_user
        - DB_PASSWORD=123456
        - JWT_KEY=jwt_key
        - JWT_REFRESH_KEY=jwt_refresh_key
        - JWT_LIFE=1h
        - JWT_REFRESH_LIFE=7d
        - RESET_PASSWORD_TOKEN=reset_password_token
        - RESET_PASSWORD_TOKEN_LIFE=15m
        - EMAIL_HOST=smtp.mailtrap.io
        - EMAIL_USER=e35adb8b10b07a
        - EMAIL_PASSWORD=7f5b18ff98f88d
        - EMAIL_PORT=2525
        - EMAIL_FROM=sn@sn.com
        - EMAIL_FROM_NAME=SN
    ports:
      - "8080:8080"
    volumes:
      - ./src:/var/www
      - /var/www/node_modules
    links:
      - database

  database:
    container_name: seven_nineteen_database
    image: mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=qwerty
      - MYSQL_DATABASE=seven_nineteen_db
      - MYSQL_USER=seven_nineteen_user
      - MYSQL_PASSWORD=123456
    volumes:
      - ./database:/var/lib/mysql
