module.exports = {
    INVALID_EMAIL: 'INVALID_EMAIL',
    EMAIL_REQUIRED: 'EMAIL_REQUIRED',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    PASSWORD_REQUIRED: 'PASSWORD_REQUIRED',
    PASSWORDS_ARE_NOT_EQUAL: 'PASSWORDS_ARE_NOT_EQUAL',
    FIRSTNAME_REQUIRED: 'FIRSTNAME_REQUIRED',
    LASTNAME_REQUIRED: 'LASTNAME_REQUIRED',
    EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
    INVALID_INPUT: 'INVALID_INPUT',
    SERVER_ERROR: 'SERVER_ERROR',
    INCORRECT_EMAIL_OR_PASSWORD: 'INCORRECT_EMAIL_OR_PASSWORD',
    INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
    NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',
    INVALID_RESET_PASSWORD_TOKEN: 'INVALID_RESET_PASSWORD_TOKEN'
};
