module.exports = {
    USER_REGISTERED_SUCCESSFULLY: 'USER_REGISTERED_SUCCESSFULLY',
    PASSWORD_UPDATED_SUCCESSFULLY: 'PASSWORD_UPDATED_SUCCESSFULLY',
    RESET_PASSWORD_TOKEN_GENERATED_SUCCESSFULLY: 'RESET_PASSWORD_TOKEN_GENERATED_SUCCESSFULLY'
};
