module.exports = {
    USER_REGISTERED_SUCCESSFULLY: 'USER_REGISTERED_SUCCESSFULLY',
    PASSWORD_UPDATED_SUCCESSFULLY: 'PASSWORD_UPDATED_SUCCESSFULLY',
    RESET_PASSWORD_TOKEN_GENERATED_SUCCESSFULLY: 'RESET_PASSWORD_TOKEN_GENERATED_SUCCESSFULLY',
    POST_CREATED_SUCCESSFULLY: 'POST_CREATED_SUCCESSFULLY',
    POST_UPDATED_SUCCESSFULLY: 'POST_UPDATED_SUCCESSFULLY',
    POST_DELETED_SUCCESSFULLY: 'POST_DELETED_SUCCESSFULLY',
    SUBSCRIPTION_ADDED_SUCCESSFULLY: 'SUBSCRIPTION_ADDED_SUCCESSFULLY',
    SUBSCRIPTION_REMOVED_SUCCESSFULLY: 'SUBSCRIPTION_REMOVED_SUCCESSFULLY',
    POST_LIKED_SUCCESSFULLY: 'POST_LIKED_SUCCESSFULLY',
    POST_UNLIKED_SUCCESSFULLY: 'POST_UNLIKED_SUCCESSFULLY',
    COMMUNITY_CREATED_SUCCESSFULLY: 'COMMUNITY_CREATED_SUCCESSFULLY'
};
